version: '3.8'

services:
  # Base de datos PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: sistema_postgres
    environment:
      POSTGRES_DB: sistema_informacion
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Locosdados1
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d
    networks:
      - sistema_network

  # Backend Spring Boot
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: sistema_backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/sistema_informacion
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Locosdados1
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - sistema_network
    volumes:
      - ./backend:/app
      - /app/target

  # Frontend React + Vite
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: sistema_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - sistema_network

volumes:
  postgres_data:

networks:
  sistema_network:
    driver: bridge 